Speed up spd_execute_command_with_list_reply
brailcom/speechd pull request #832
Opened 2023-06-02 00:41 UTC by novalis

spd_execute_command_with_list_reply was accidentally quadratic: it would start by searching the string for one \r\n, then it would search for two, then for three...  I have 15,000 voices (I have no idea why; it seems to be the default Debian config), so this was quite slow.

For me, this improves the performance of spd_list_synthesis_voices from 1.5s to 0.5s.

2023-06-05 21:46 UTC, sthibaul commented
Thanks for your patch, it looks promising :)

I'd however rather not copy/paste the implementation of `get_param_str`.

It seems to me like everything in `get_param_str` after the for loop could be replaced by a call to your function, thus factorizing everything that can be?

2023-06-05 23:53 UTC, sthibaul requested changes

2023-06-05 23:53 UTC, sthibaul commented on src/api/c/libspeechd.c
> +	ret = setvbuf(connection->stream, NULL, _IOLBF, SPD_REPLY_BUF_SIZE);
Please do not mix with other fixes :)

2023-06-06 01:47 UTC, novalis commented on src/api/c/libspeechd.c
> +	ret = setvbuf(connection->stream, NULL, _IOLBF, SPD_REPLY_BUF_SIZE);
oops

2023-06-06 09:50 UTC, sthibaul commented on src/api/c/libspeechd.c
> +	if (*pos_end == 0) {
Noticing this just now: there shouldn't be a `*`, it's really the pointer that needs to be tested. You can leave the code as it is.

2023-06-06 13:42 UTC, sthibaul approved these changes

2023-06-06 13:42 UTC, merged

2023-06-06 13:43 UTC, sthibaul commented
Thanks!